version: 2.1

# Make checkout faster
# https://circleci.com/developer/orbs/orb/guitarrapc/git-shallow-clone
orbs:
  git-shallow-clone: guitarrapc/git-shallow-clone@2.4.0

# Define test and build commands
commands:
  setup:
    steps:
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
  build:
    steps:
      - setup
      - checkout
      - run: echo "this is the build job"
      - run:
          name: Build to dockerhub for test
          command: |
            docker build -t $DOCKER_USERNAME/azure-docker-react-advanced-dev:latest .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push $DOCKER_USERNAME/azure-docker-react-advanced-dev:latest
  test:
    steps:
      - setup
      - run: echo "this is the test job"
      - run:
          name: unit test
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker run $DOCKER_USERNAME/azure-docker-react-advanced-dev:latest sh -c "echo hello"
  deploy:
    steps:
      - setup
      - run: echo "this is the deploy job"
      - run:
          name: Push tested image to auto-deploy
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker pull $DOCKER_USERNAME/azure-docker-react-advanced-dev:latest
            docker tag $DOCKER_USERNAME/azure-docker-react-advanced-dev:latest $DOCKER_USERNAME/azure-docker-react-advanced:latest
            docker push $DOCKER_USERNAME/azure-docker-react-advanced:latest

# Define the executors for this project
executors:
  docker-executor:
    docker:
      - image: circleci/node:latest

# Define the jobs we want to run for this project
jobs:
  # Specify build executors
  build-with-docker:
    executor: docker-executor
    steps:
      - build
  # Specify test executors
  test-with-docker:
    executor: docker-executor
    steps:
      - test
  # Specify deploy build executors
  deploy-with-docker:
    executor: docker-executor
    steps:
      - deploy

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-with-docker
      - test-with-docker:
          requires:
            - build-with-docker
      - deploy-with-docker:
          requires:
            - test-with-docker
