version: 2.1


# Define the executors for this project
executors:
 docker-executor:
   docker:
     - image: circleci/openjdk:9.0.4-12


# Define the jobs we want to run for this project
jobs:
  # Define build
  build:
    docker:
      - image: raychung/azure-docker-react-advanced:latest
        auth:
          username: raychung
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the build job"
      - run:
          name: Build and push Docker image
          command: |
            docker build -t raychung/azure-docker-react-advanced:latest .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push raychung/azure-docker-react-advanced:latest

  # Define test
  test:
    docker:
      - image: raychung/azure-docker-react-advanced:latest
        auth:
          username: raychung
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"

  # Specify build executors
  build-with-docker:
    executor: docker-executor
    steps:
      - build


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-with-docker
      - test

