version: 2.1

# Define test and build commands
commands:
  # test:
  #   docker:
  #     - image: raychung/azure-docker-react-advanced:latest
  #       auth:
  #         username: $DOCKER_USERNAME
  #         password: $DOCKER_PASSWORD  # context / project UI env-var reference
  #   steps:
  #     - checkout
  #     - run: echo "this is the test job"
  build:
    steps:
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      - checkout
      - run: echo "this is the build job"
      - run:
          name: Build and push Docker image
          command: |
            docker build -t raychung/azure-docker-react-advanced:latest .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push raychung/azure-docker-react-advanced:latest


# Define the executors for this project
executors:
 docker-executor:
   docker:
     - image: circleci/openjdk:9.0.4-12


# Define the jobs we want to run for this project
jobs:
  # Specify build executors
  build-with-docker:
    executor: docker-executor
    steps:
      - build
  # Specify test executors
  # test-with-docker:
  #   executor: docker-executor
  #   steps:
  #     - test


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-with-docker
      # - test-with-docker

